language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7

install:
  - composer self-update
  - composer install --prefer-dist --optimize-autoloader

script:
  - php ./vendor/bin/phpunit -c phpunit.xml --coverage-text

notifications:
  email: false

matrix:
  fast_finish: true
  allow_failures:
    - php: 7
