language: php

sudo: false

env:
    global:
        - PHP_LATEST_VERSION=0

matrix:
    fast_finish: true
    include:
        - php: 7.0
        - php: 7.1
          env: PHP_LATEST_VERSION=1

cache:
  directories:
    - $HOME/.composer

install:
  - composer install --prefer-dist

script:
  - sh .travis.run-tests.sh

notifications:
  email: false
